services:
  api:
    env_file:
      - .env.docker
    environment:
      - ENV=docker
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./images:/code/images
    depends_on:
      redis-service:
        condition: service_started
      mongodb-service:
        condition: service_started
  workers:
    scale: 3
    env_file:
      - .env.docker
    environment:
      - ENV=docker
    build:
      context: .
      dockerfile: Dockerfile.workers
      args:
        - ENV:${ENV:-docker}
    volumes:
      - .:/app
      - ./images:/code/images
    depends_on:
      redis-service:
        condition: service_started
      mongodb-service:
        condition: service_started
  mongodb-service:
    image: mongo:latest
    restart: always
    env_file:
      - .env.docker
    ports:
     - "27017:27017"
    environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: admin
  redis-service:
    image: redis:latest
    ports:
      - "6379:6379"
  flower-service:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis-service:6379/0', '--port=5555' ]
    ports:
      - 5557:5555
    depends_on:
      - redis-service
