version: "3.8"
services:
  ai-platform-api:
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./images:/code/images
  image-generator-service:
    env_file:
      - .env.docker
    environment:
      - ENV=docker
    build:
      context: .
      dockerfile: Dockerfile.workers
      args:
        - ENV:${ENV:-docker}
    volumes:
      - .:/app
      - ./images:/code/images
  mongodb-service:
    image: mongo:latest
    env_file:
      - .env.local
    ports:
     - "27017:27017"
    environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: admin

